---
abstract: 'Dancer plugin to cache response content (and anything else)'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Dancer2: '0.200000'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  HTTP::Request::Common: '0'
  Plack::Test: '0'
  Test::More: '0'
  lib: '0'
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-Cache-CHI
provides:
  Dancer2::Plugin::Cache::CHI:
    file: lib/Dancer2/Plugin/Cache/CHI.pm
    version: v2.0.1
requires:
  CHI: '0'
  Carp: '0'
  Dancer2: '0.200000'
  Dancer2::Plugin: '0'
  List::MoreUtils: '0'
  Moo: '1.000007'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dancer2-Plugin-Cache-CHI/issues
  homepage: https://github.com/yanick/Dancer2-Plugin-Cache-CHI
  repository: https://github.com/yanick/Dancer2-Plugin-Cache-CHI.git
version: 2.0.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Alexis Sukrieh <sukria@cpan.org>'
  - 'David Precious <davidp@preshweb.co.uk>'
  - 'Franck Cuny <franck@lumberjaph.net>'
  - 'girlwithglasses <gwg@Cygnus-X1.local>'
  - 'Kim Hansen <kim@rthansen.dk>'
  - 'Perlover <perlover@perlover.com>'
  - 'Peter Mottram <peter@sysnix.com>'
  - 'Yanick Champoux <yanick@babyl.ca>'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
